name: Run Battery of Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --no-root --extras "dev"
    - name: Lint with Ruff
      run: poetry run ruff check ./RTN
    - name: Check imports with isort
      run: poetry run isort --check-only ./RTN
    - name: Type check
      run: poetry run pyright
    - name: Run Tests
      run: poetry run pytest
    - name: Coverage Report
      run: |
        poetry run coverage run -m pytest
        poetry run coverage xml
        poetry run coverage report -m
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
